[project]
name = "uv-workflow"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

# uv init --lib
# Makes src directory for sources
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"